# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Apr 12 12:38:24 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 969)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("omega.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.medSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medSpinBox.sizePolicy().hasHeightForWidth())
        self.medSpinBox.setSizePolicy(sizePolicy)
        self.medSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.medSpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.medSpinBox.setDecimals(3)
        self.medSpinBox.setMaximum(99999999.0)
        self.medSpinBox.setProperty("value", 1.0)
        self.medSpinBox.setObjectName(_fromUtf8("medSpinBox"))
        self.horizontalLayout_6.addWidget(self.medSpinBox)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.nedSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nedSpinBox.sizePolicy().hasHeightForWidth())
        self.nedSpinBox.setSizePolicy(sizePolicy)
        self.nedSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.nedSpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.nedSpinBox.setDecimals(3)
        self.nedSpinBox.setMinimum(-999999990.0)
        self.nedSpinBox.setMaximum(99999999.0)
        self.nedSpinBox.setProperty("value", 0.0)
        self.nedSpinBox.setObjectName(_fromUtf8("nedSpinBox"))
        self.horizontalLayout_6.addWidget(self.nedSpinBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.concreteCombo = QtGui.QComboBox(self.groupBox_3)
        self.concreteCombo.setMinimumSize(QtCore.QSize(0, 25))
        self.concreteCombo.setMaximumSize(QtCore.QSize(16777215, 25))
        self.concreteCombo.setObjectName(_fromUtf8("concreteCombo"))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.concreteCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.concreteCombo)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.fcdSpinBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fcdSpinBox.sizePolicy().hasHeightForWidth())
        self.fcdSpinBox.setSizePolicy(sizePolicy)
        self.fcdSpinBox.setDecimals(3)
        self.fcdSpinBox.setMaximum(9999999.99)
        self.fcdSpinBox.setProperty("value", 11.33)
        self.fcdSpinBox.setObjectName(_fromUtf8("fcdSpinBox"))
        self.horizontalLayout_7.addWidget(self.fcdSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.widthSpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.widthSpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widthSpinBox.setSingleStep(0.1)
        self.widthSpinBox.setProperty("value", 1.0)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.horizontalLayout_8.addWidget(self.widthSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.heightSpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.heightSpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.heightSpinBox.setSingleStep(0.1)
        self.heightSpinBox.setProperty("value", 1.0)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.horizontalLayout_10.addWidget(self.heightSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_9.addWidget(self.label_14)
        self.d1SpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d1SpinBox.sizePolicy().hasHeightForWidth())
        self.d1SpinBox.setSizePolicy(sizePolicy)
        self.d1SpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.d1SpinBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.d1SpinBox.setProperty("value", 10.0)
        self.d1SpinBox.setObjectName(_fromUtf8("d1SpinBox"))
        self.horizontalLayout_9.addWidget(self.d1SpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.outD = QtGui.QLineEdit(self.groupBox_4)
        self.outD.setMinimumSize(QtCore.QSize(0, 25))
        self.outD.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outD.setSizeIncrement(QtCore.QSize(0, 0))
        self.outD.setReadOnly(True)
        self.outD.setObjectName(_fromUtf8("outD"))
        self.gridLayout_2.addWidget(self.outD, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.outZs = QtGui.QLineEdit(self.groupBox_4)
        self.outZs.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outZs.setReadOnly(True)
        self.outZs.setObjectName(_fromUtf8("outZs"))
        self.gridLayout_2.addWidget(self.outZs, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_15.addWidget(self.label)
        self.outMuS1Ed = QtGui.QLineEdit(self.groupBox)
        self.outMuS1Ed.setMinimumSize(QtCore.QSize(0, 25))
        self.outMuS1Ed.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outMuS1Ed.setReadOnly(True)
        self.outMuS1Ed.setObjectName(_fromUtf8("outMuS1Ed"))
        self.horizontalLayout_15.addWidget(self.outMuS1Ed)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.outOmega1 = QtGui.QLineEdit(self.groupBox)
        self.outOmega1.setMinimumSize(QtCore.QSize(0, 25))
        self.outOmega1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outOmega1.setReadOnly(True)
        self.outOmega1.setObjectName(_fromUtf8("outOmega1"))
        self.gridLayout.addWidget(self.outOmega1, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.outEpsS1 = QtGui.QLineEdit(self.groupBox)
        self.outEpsS1.setMinimumSize(QtCore.QSize(0, 25))
        self.outEpsS1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outEpsS1.setReadOnly(True)
        self.outEpsS1.setObjectName(_fromUtf8("outEpsS1"))
        self.gridLayout.addWidget(self.outEpsS1, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.outXi = QtGui.QLineEdit(self.groupBox)
        self.outXi.setMinimumSize(QtCore.QSize(0, 25))
        self.outXi.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outXi.setReadOnly(True)
        self.outXi.setObjectName(_fromUtf8("outXi"))
        self.gridLayout.addWidget(self.outXi, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.outEpsC2 = QtGui.QLineEdit(self.groupBox)
        self.outEpsC2.setMinimumSize(QtCore.QSize(0, 25))
        self.outEpsC2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outEpsC2.setReadOnly(True)
        self.outEpsC2.setObjectName(_fromUtf8("outEpsC2"))
        self.gridLayout.addWidget(self.outEpsC2, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.outZeta = QtGui.QLineEdit(self.groupBox)
        self.outZeta.setMinimumSize(QtCore.QSize(0, 25))
        self.outZeta.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outZeta.setReadOnly(True)
        self.outZeta.setObjectName(_fromUtf8("outZeta"))
        self.gridLayout.addWidget(self.outZeta, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.outVSigma = QtGui.QLineEdit(self.groupBox)
        self.outVSigma.setMinimumSize(QtCore.QSize(0, 25))
        self.outVSigma.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outVSigma.setReadOnly(True)
        self.outVSigma.setObjectName(_fromUtf8("outVSigma"))
        self.gridLayout.addWidget(self.outVSigma, 2, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.outAs1 = QtGui.QLineEdit(self.groupBox_5)
        self.outAs1.setMinimumSize(QtCore.QSize(0, 25))
        self.outAs1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outAs1.setReadOnly(True)
        self.outAs1.setObjectName(_fromUtf8("outAs1"))
        self.horizontalLayout_17.addWidget(self.outAs1)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_18.addWidget(self.label_17)
        self.outAs2 = QtGui.QLineEdit(self.groupBox_5)
        self.outAs2.setMinimumSize(QtCore.QSize(0, 25))
        self.outAs2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.outAs2.setReadOnly(True)
        self.outAs2.setObjectName(_fromUtf8("outAs2"))
        self.horizontalLayout_18.addWidget(self.outAs2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Omega", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Schnittgrößen", None))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bemessungsmoment M<span style=\" vertical-align:sub;\">Ed</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>M<span style=\" vertical-align:sub;\">Ed </span>[kNm]</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>N<span style=\" vertical-align:sub;\">Ed</span> [kN]</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Beton", None))
        self.concreteCombo.setItemText(0, _translate("MainWindow", "C12/15", None))
        self.concreteCombo.setItemText(1, _translate("MainWindow", "C16/20", None))
        self.concreteCombo.setItemText(2, _translate("MainWindow", "C20/25", None))
        self.concreteCombo.setItemText(3, _translate("MainWindow", "C25/30", None))
        self.concreteCombo.setItemText(4, _translate("MainWindow", "C30/37", None))
        self.concreteCombo.setItemText(5, _translate("MainWindow", "C35/45", None))
        self.concreteCombo.setItemText(6, _translate("MainWindow", "C40/50", None))
        self.concreteCombo.setItemText(7, _translate("MainWindow", "C45/55", None))
        self.concreteCombo.setItemText(8, _translate("MainWindow", "C50/60", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>f<span style=\" vertical-align:sub;\">cd </span>[MN/m<span style=\" vertical-align:super;\">2</span>]</p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Geometrie", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Breite b [m]</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Höhe h [m]</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Bewehrungsabstand d1 [cm]</p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Statische Nutzhöhe d [m]</p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Abstand Bewehrung - Schwerpunkt z<span style=\" vertical-align:sub;\">s</span> [m]</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Statische Werte", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>μ<span style=\" vertical-align:sub;\">s1,Ed</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>ω<span style=\" vertical-align:sub;\">1</span></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">s1</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>ξ</p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">c2</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>ζ</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>v<span style=\" vertical-align:sub;\">σ</span></p></body></html>", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Bewehrung", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Zugbewehrung A<span style=\" vertical-align:sub;\">s1 </span>[cm<span style=\" vertical-align:super;\">2</span>]</p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Druckbewehrung A<span style=\" vertical-align:sub;\">s2 </span>[cm<span style=\" vertical-align:super;\">2</span>]</p></body></html>", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&help", None))
        self.action_Help.setText(_translate("MainWindow", "&Help", None))
        self.actionAbout.setText(_translate("MainWindow", "about ...", None))

